default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>

development:
  <<: *default
  database: anyur_development

test:
  <<: *default
  database: anyur_test

production:
  primary: &primary_production
    <<: *default
    database: anyur_production
  cache:
    <<: *primary_production
    database: anyur_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: anyur_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: anyur_production_cable
    migrations_paths: db/cable_migrate
